### ISSUE TITLE
version question？

### ISSUE THREAD

**Issue by Mr111222** [kitorv/vue-ui-docs#2]

**Comment by Mr111222** [comment]
@kitorv                                         vue-loader@15+  webpack@4+  error                                                                                                                                            ERROR in ./src/docs/el-alert.md?vue&type=template&id=67d78cc8 (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-markdown-loader??ref--6!./src/docs/el-alert.md?vue&type=template&id=67d78cc8)
(Emitted value instead of an instance of Error)
  Error compiling template:
  module.exports = require("!!vue-loader!../../node_modules/vue-markdown-loader/lib/markdown-compiler.js?raw!./el-alert.md?vue&type=template&id=67d78cc8");
  - Component template requires a root element, rather than just text.

 @ ./src/docs/el-alert.md?vue&type=template&id=67d78cc8 1:0-197 1:0-197
 @ ./node_modules/vue-loader/lib!./node_modules/vue-markdown-loader/lib/markdown-compiler.js?raw!./src/docs/el-alert.md
 @ ./src/docs/el-alert.md
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by kitorv** [comment]
这个是vue-cli2.9环境搭建的，默认是webpack3.X升级的话，就需要自己调整vue-cli自带的配置文件，
如果要用vue-cli 3.0默认就是webpack4.X的配置，可以参考 https://github.com/kitorv/study-notes/blob/master/vue/VUE-01.md  在结合最新的vue-cli 3.0配置整合

**Comment by Mr111222** [comment]
Thanks

**Comment by Mr111222** [comment]
@kitorv   vue-loader@15+   vue-cli3  ---->  "vue-loader": "^13.3.0"     Error compiling template:
module.exports = require("!!vue-loader!../../node_modules/vue-markdown-loader/lib/markdown-compiler.js?raw!./el-alert.md?vue&type=template&id=67d78cc8");

**Comment by kitorv** [comment]
vue-cli3.0重新搭建 https://github.com/kitorv/vue-md-doc.git  vue-cli3.0的webpack配置文件不一样所以需要调整下

**Comment by Mr111222** [comment]
resolve
