### ISSUE TITLE
请问如何开发实时编译md文件，实时改变UI效果

### ISSUE THREAD

**Issue by Mr111222** [kitorv/vue-ui-docs#3]
<button>按钮</button>---> ui 显示为按钮 
<button>按1钮</button>---> ui 显示为按钮1,而且还是要结合这个vue-markdown-loader来做

**Comment by kitorv** [comment]
这个改了md文件就本身会实时编译

**Comment by Mr111222** [comment]
是，但是跟我的改变不是一个意思，你可以查看一下vuep这个依赖包，我要实现跟他一样的功能，但是我不知道怎么融合到一起，https://cinwell.com/vuep/#/?id=demo 希望能尽快回复我

**Comment by kitorv** [comment]
你可以用 https://www.npmjs.com/package/marked 或者 https://www.npmjs.com/package/markdown-it 之类的可以解析markdown的类库  然后你左侧的数据变化就调用解析markdown的内容  然后将内容用vue.component  包装成组件在将组件渲染在右侧  就实时变化了

**Comment by Mr111222** [comment]
![image](https://user-images.githubusercontent.com/23070808/49195454-27b24680-f3c2-11e8-877d-e06be8564c81.png)
我现在就是用您的这个项目，markdown-it依赖包已经在使用了，但是不知道怎么在webpack.base.config.js里面写

**Comment by kitorv** [comment]
![image](https://user-images.githubusercontent.com/16646917/49195691-1a498c00-f3c3-11e8-8a25-6b4478c3a8a8.png)
你就是需要左侧编码markdown代码 右侧直接展示么  还是什么效果
如果左侧代码右侧预览的话，配置webpack是不行webpack是打包后，就是将markdown解析成vue组件，你要实时预览就写个  vue组件左侧代码 然后将 代码编译右侧初始化就好了

**Comment by Mr111222** [comment]
左侧编码markdown代码 右侧直接展示html实际渲染效果，但是左侧编辑改变，右侧也可以变化
