### ISSUE TITLE
期待老铁的代码实时编译功能

### ISSUE THREAD

**Issue by Mr111222** [kitorv/vue-ui-docs#4]

**Comment by kitorv** [comment]
实时编译可以直接集成类似codesanbox，自己写一个没法支持代码中含有import的外部依赖

**Comment by kitorv** [comment]
我实际项目实践过外部依赖import required等还有图片等等使用外部资源实时编译很多问题，主要用vue的`Vue.compile( template )`这个API，实际还是很多限制，直接集成第三方的API也简单功能也强大
