### ISSUE TITLE
md 文档中如果有jsx语法 怎么给项目工程jsx编译

### ISSUE THREAD

**Issue by shiliangL** [kitorv/vue-ui-docs#5]
![image](https://user-images.githubusercontent.com/24687496/96332060-9f5fec00-1094-11eb-89f1-1da84da453b9.png)
![image](https://user-images.githubusercontent.com/24687496/96332076-aedf3500-1094-11eb-8790-d38438c04c4e.png)

**Comment by kitorv** [comment]
代码已经支持jsx渲染，具体改动可以查看[https://github.com/kitorv/vue-ui-docs/commit/ff4e097abc51d9684b21b73c225acd8a76b83b7e](https://github.com/kitorv/vue-ui-docs/commit/ff4e097abc51d9684b21b73c225acd8a76b83b7e)
