### ISSUE TITLE
你好， 你这个能扩展嘛

### ISSUE THREAD

**Issue by hangjob** [kitorv/vue-ui-docs#6]
:::snippet 通过 v-button 标签初始化按钮。
#### 我在这里添加了个小标题
我在这里也添加了点描述
```html
<template>
  <div>
    <v-button>Default</v-button>
  </div>
</template>
```
:::

程序就挂掉了，在loader中如何配置？

**Comment by kitorv** [comment]
加标题和描述想展示在哪里，还是只要能够渲染，我给你个简单的代码示例就可以

**Comment by hangjob** [comment]
```html
<template>
  <div class="vc-snippet">
    <div class="vc-snippet--demo">
      我想加在这里
      <!-- 代码生成vue示例 -->
      <slot name="source" />
    </div>
    <div class="vc-snippet--desc">
      <!-- 示例描述说明 -->
      <slot name="desc" />
      <span class="vc-snippet--icon-code" @click="showCode = !showCode">
        <img alt="code" :src="codeIconSrc" />
      </span>
    </div>
    <div v-show="showCode" class="vc-snippet--code">
      <!-- 示例代码高亮显示 -->
      <slot name="code" />
    </div>
  </div>
</template>
```
![image](https://user-images.githubusercontent.com/22078920/126598212-75b1571d-bbe2-44ae-938d-cb8d332f735b.png)

**Comment by hangjob** [comment]
对应的 .md 应该是这样的

:::snippet 通过 v-button 标签初始化按钮。

# 我想加载这里1

我想加载这里2

```html
<template>
  <div>
    <v-button>Default</v-button>
  </div>
</template>
```
:::

**Comment by kitorv** [comment]
1. 在这里查找最新的 ```html 开始位置 就是要编译成vue单组件的代码，其他的跳过markdown-it会自动渲染
<img width="850" alt="image" src="https://user-images.githubusercontent.com/16646917/128037489-b89d4773-cfae-4d9a-ae46-83bd8d555741.png">
2. 代码示例
<img width="430" alt="image" src="https://user-images.githubusercontent.com/16646917/128037715-44c4c64a-e99a-45c5-9376-89a697128a3f.png">
3. 展示效果
<img width="800" alt="image" src="https://user-images.githubusercontent.com/16646917/128038432-ed2e2096-673b-4528-bd1e-40c195ef7bd6.png">

**Comment by hangjob** [comment]
我跟你提的问题，我研究了2天解决了，其实想看下你有没有更好的解决方案，你竟然关闭它了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月3日(星期二) 晚上11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kitorv/vue-ui-docs] 你好， 你这个能扩展嘛 (#6)





  
在这里查找最新的 ```html 开始位置 就是要编译成vue单组件的代码，其他的跳过markdown-it会自动渲染
  

 2. 代码示例 

 3. 展示效果 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kitorv** [comment]
我上面已经给你代码示例，我实际照这么使用也可以正常渲染,能够正常渲染，吧对应数据提取出来放到你想放的位置就基本可以实现
