### ISSUE TITLE
模板变量有提示报错信息

### ISSUE THREAD

**Issue by hangjob** [kitorv/vue-ui-docs#7]
你好，想问下这种问题有解决方案嘛？

![image](https://user-images.githubusercontent.com/22078920/127313022-d47c87e5-3e15-4dc4-b330-fe9af68c2cc5.png)
![image](https://user-images.githubusercontent.com/22078920/127313107-79e0c9ff-1c33-403f-b8f5-2d468e60063c.png)

**Comment by kitorv** [comment]
已经修复，核心代码
<img width="826" alt="image" src="https://user-images.githubusercontent.com/16646917/128039087-1633da81-6b46-4ad0-9658-9ecbd692c218.png">
